<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net48;netstandard2.0</TargetFrameworks>
    <RootNamespace>GeoMagSharp</RootNamespace>
    <AssemblyName>GeoMagSharp</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
    <None Include="..\..\coefficient\**\*" Pack="true" PackagePath="coefficient" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\coefficient\**\*.COF" Link="coefficient\%(RecursiveDir)%(Filename)%(Extension)">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <PackageCopyToOutput>true</PackageCopyToOutput>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Data\iscwsa-uncertainty.json" />
    <EmbeddedResource Include="Data\wmm-error-model.json" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="GeoMagSharp.Tests" />
    <InternalsVisibleTo Include="GeoMagSharp.GUI" />
  </ItemGroup>

</Project>
